apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: some-container
    image: g1g1/py-kube:0.2
    command: ["/bin/bash", "-c", "while true ; do sleep 10 ; done"]
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false

